---------------------------------------------------------------------------
-- VEIC045 - ASSOCIA FLUXO COM VEÍCULO USADO
-- AUTOR ANDRE FOGAÇA
-- VER 03 - 14/07/2016
---------------------------------------------------------------------------

SELECT
   (SELECT FIRST_VALUE(TB1.VLOJ_DATACON_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "DT_CONTATO"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_HORACON_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "HORA"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_TIPOCON_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "TIPO"
  ,REPLACE((SELECT FIRST_VALUE(TB1.NTAB_DESCRIC_75) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1),'VENDEDORES','') AS "SETOR*"
  ,(SELECT FIRST_VALUE(TB1.DVEN_NOMEVEN_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "VENDEDOR"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_NOMECLI_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "CLIENTE+"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_RESULTA_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "RESULTADO"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_CONCLUS_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "OBS RESULTADO"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_DDDFO01_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "DDD1"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_TELEF01_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "TEL1"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_DDDFO02_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "DDD2"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_TELEF02_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "TEL2"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_MODCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "INTERESSE"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_ANOCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "ANO"
  ,(SELECT FIRST_VALUE(TB1.VLOJ_VALCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1,VLOJ_HORALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1) AS "VLR_INT$"
  ,CASE
       WHEN  TB1.VLOJ_MODCOMP_1  = ' ' THEN 0
       WHEN  TB1.VLOJ_MODCOMP_1 != ' ' THEN
            (SELECT COUNT(*)
             FROM SGVVEI V
             WHERE V.VVEI_DESCMOD_1 LIKE '%'||RTRIM(SUBSTR((SELECT FIRST_VALUE(TB1.VLOJ_MODCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1)||' ',1,INSTR((SELECT FIRST_VALUE(TB1.VLOJ_MODCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATALTE_1 DESC) FROM SGVLOG TB2 WHERE ROWNUM=1)||' ',' ',1,1)))||'%'
               AND V.VVEI_STATUSV_1 !='V'
               AND V.VVEI_TIPOVEI_1='U') END AS "ESTOQUE"
FROM
(SELECT
   *
 FROM SGVLOJ L1
   LEFT JOIN CADVEN   C1 ON (C1.DVEN_CODUSER_1=L1.VLOJ_CODUSER_1)
   LEFT JOIN SINTAB75 T1 ON (C1.DVEN_CODGRUP_1=T1.NTAB_CODGRUP_75))TB1
WHERE TB1.VLOJ_DATAORI_1 BETWEEN :DT_INICIO_D AND :DT_FINAL_D
  AND TB1.VLOJ_OBJCONT_1 = 'B - VENDA SEMI-NOVO'
  AND TB1.VLOJ_PROPOST_1  = ' '
  AND TB1.VLOJ_RESULTA_1 != 'FATURAMENTO DO VEICULO'
;