---------------------------------------------------------------------------
-- VEIC045 - ASSOCIA FLUXO COM VEÍCULO USADO
-- AUTOR ANDRE FOGAÇA
-- VER 04 - 03/08/2016
---------------------------------------------------------------------------

SELECT DISTINCT
   FIRST_VALUE(TB1.VLOJ_DATACON_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "DT_CONTATO"
  ,FIRST_VALUE(TB1.VLOJ_HORACON_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "HORA"
  ,FIRST_VALUE(TB1.VLOJ_TIPOCON_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "TIPO"
  ,REPLACE(FIRST_VALUE(T1.NTAB_DESCRIC_75) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC),'VENDEDORES','') AS "SETOR*"
  ,FIRST_VALUE(C1.DVEN_NOMEVEN_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "VENDEDOR"
  ,FIRST_VALUE(TB1.VLOJ_NOMECLI_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "CLIENTE+"
  ,FIRST_VALUE(TB1.VLOJ_RESULTA_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "RESULTADO"
  ,FIRST_VALUE(TB1.VLOJ_CONCLUS_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "OBS RESULTADO"
  ,FIRST_VALUE(TB1.VLOJ_DDDFO01_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "DDD1"
  ,FIRST_VALUE(TB1.VLOJ_TELEF01_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "TEL1"
  ,FIRST_VALUE(TB1.VLOJ_DDDFO02_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "DDD2"
  ,FIRST_VALUE(TB1.VLOJ_TELEF02_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "TEL2"
  ,FIRST_VALUE(TB1.VLOJ_MODCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "INTERESSE"
  ,FIRST_VALUE(TB1.VLOJ_ANOCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "ANO"
  ,FIRST_VALUE(TB1.VLOJ_VALCOMP_1) IGNORE NULLS OVER (PARTITION BY TB1.VLOJ_TELEF01_1 ORDER BY TB1.VLOJ_DATAORI_1,TB1.VLOJ_HORAORI_1 DESC) AS "VLR_INT$"
FROM SGVLOJ TB1
   LEFT JOIN CADVEN   C1 ON (C1.DVEN_CODUSER_1=TB1.VLOJ_CODUSER_1)
   LEFT JOIN SINTAB75 T1 ON (C1.DVEN_CODGRUP_1=T1.NTAB_CODGRUP_75)
WHERE TB1.VLOJ_DATAORI_1 BETWEEN :DT_INICIO_D AND :DT_FINAL_D
  AND TB1.VLOJ_OBJCONT_1 = 'B - VENDA SEMI-NOVO'
  AND TB1.VLOJ_PROPOST_1  = ' '
  AND TB1.VLOJ_RESULTA_1 != 'FATURAMENTO DO VEICULO'
;